### ISSUE TITLE
No detection and tracking in the video

### ISSUE THREAD

**Issue by Teezq** [emasterclassacademy/Single-Multiple-Custom-Object-Detection-and-Tracking#11]
Hi @emasterclassacademy , I have ran into a problem where there is no detection or bounding box at my output video. I have manually printed out the boxs, scores and classes, but these parameters only return values on the first frame while other remaining frames just remains an empty list. Does anyone here encounter such issue? Or did anyone manage to solve it? I am aware that I only generated the 3 files when converting yolo to tensorflow: checkpoint, yolov3.tf.data-00000-of-00001, yolov3.tf.index. Could this be the problem? If yes, does anyone has experience with this?

**Comment by Teezq** [comment]
Any hint guys? So I have confirmed that the yolo detection runs on the first frame, deepsort tracking doesnt since there is no update. When begining from second frame, both just stop running and return empty values.

**Comment by Teezq** [comment]
![image](https://user-images.githubusercontent.com/87978642/127104107-7784c347-fe7a-4a58-acf9-d3aa4d073084.png)

**Comment by kenca5ey** [comment]
Hi @Teezq - Did you manage to find a solution to this issue? I am experiencing the exact same issue as you were, where the first frame has a detection but all of the arrays for detections are zeros thereafter

**Comment by kenca5ey** [comment]
Hi @emasterclassacademy - Great work! Would really appreciate any insights on why yolo.predict runs correctly on the first call to the function but on subsequent calls to yolo.predict only empty arrays are returned. Any idea why this might be?

**Comment by acschristoph** [comment]
Hey guys I have same issue did u resolve it ?

**Comment by kenca5ey** [comment]
Hi @acschristoph - I am not sure what changed to cause this issue so I didn't end up sticking with this. But as a workaround, calling the model itself yolo() will likely work on subsequent iteration calls.

**Comment by vini-c-costa** [comment]
Hey guys, @Teezq @kenca5ey @acschristoph

Have you solved this issue? I'm having the same problem.
