### ISSUE TITLE
Wasn't able to run with GPU, but works with CPU

### ISSUE THREAD

**Issue by Teezq** [emasterclassacademy/Single-Multiple-Custom-Object-Detection-and-Tracking#12]
So I faced the issue where only the first frame is detected and tracked when I running the object_tracker.py using tensorflow-gpu. However, once I uninstalled tensorflow-gpu and replaced it with tensorflow-cpu (latest version since I am using python 3.9), it works flawlessly. Does anyone one faced this issue? I am using GTX 1050 on my laptop which I believe it should run since the author @emasterclassacademy used GTX1050 ti in Youtube video. FYI, I am running on latest CUDA version 11 as well. Below is the full GPU information I have gotten when I ran with tensorflow-gpu. 

![image](https://user-images.githubusercontent.com/87978642/127109740-ff063a1c-6938-4ab1-8f9b-f645c0c2ed03.png)

**Comment by acschristoph** [comment]
@Teezq hey did u resolve it
