### ISSUE TITLE
Problem with detection

### ISSUE THREAD

**Issue by PiotrG1996** [emasterclassacademy/Single-Multiple-Custom-Object-Detection-and-Tracking#5]
I wonder why it doesn't detect any object from the video frames.
Did I miss something after converting yolov3 model?

My results:

![Screenshot-20210528125318-1282x717](https://user-images.githubusercontent.com/52200870/119973544-e52e4c80-bfb3-11eb-81a4-edd9e392007c.png)

**Comment by Intruder31** [comment]
Same issue. I have a custom trained YOLOv3 model, converted that to tf format using the convert.py in this repo; doesn't detect anything. Are you using custom trained model too?

For me the pre-trained YOLOv3 works though.

**Comment by PiotrG1996** [comment]
I used official weights from this source: https://pjreddie.com/darknet/yolo/

None of them worked for me. Could you share .tf files? I have no idea what's wrong with my files.

**Comment by Intruder31** [comment]
Sure I could share them. What platform do you want me to upload them on? 

Also, would love to take a look at your .tf files to resolve my issue with custom trained weights. 

I have attached the list of files as well as their sizes (if that helps) after conversion. The highlighted ones are newly formed.
<img width="855" alt="Screenshot 2021-05-30 at 11 41 16 PM" src="https://user-images.githubusercontent.com/44464466/120115270-8d086d80-c1a0-11eb-8ea7-5397aa834d3a.png">

**Comment by Intruder31** [comment]
Ok I guess I'd downloaded the wrong weights and I'm guessing you have too. 

You will need to download weights from https://pjreddie.com/media/files/yolov3.weights  (~248 MB) and then convert them to .tf

To train on custom datasets, we need convolutional weights that are pre-trained on Imagenet. These are found at https://pjreddie.com/media/files/darknet53.conv.74 (~162.5 MB)

**Comment by PiotrG1996** [comment]
Thanks, this fixed my issue. Nonetheless, this algorithm seems to be very memory consuming. GPU results on gtx 1080 2-3 fps.
Have you tested tensorflow lite with it? 
![results](https://user-images.githubusercontent.com/52200870/120156250-185e1f00-c1f2-11eb-9a2e-f460d4f456c8.png)
